import { createProduct } from "./firestore";

const DEMO_PRODUCTS = [
  {
    title: "SaaS Starter Kit — Next.js + Stripe",
    slug: "saas-starter-nextjs-stripe",
    shortDescription: "Production-ready SaaS boilerplate with auth, billing, and admin dashboard.",
    description: "A complete SaaS starter kit built with Next.js 14, Tailwind CSS, Prisma ORM, and Stripe subscriptions. Includes multi-tenant auth, customer portal, webhook handling, team management, and a polished admin dashboard. Save 200+ hours of setup work.",
    price: 79,
    originalPrice: 129,
    category: "saas",
    version: "2.1.0",
    techStack: ["Next.js", "TypeScript", "Tailwind CSS", "Prisma", "Stripe", "PostgreSQL"],
    features: [
      "Google & GitHub OAuth + Email Magic Link",
      "Stripe subscriptions with multiple pricing tiers",
      "Customer billing portal",
      "Admin dashboard with user management",
      "Team workspaces & invitations",
      "Email notifications (Resend)",
      "Dark/light mode",
      "Fully typed with TypeScript",
    ],
    tags: ["nextjs", "saas", "stripe", "typescript", "prisma"],
    thumbnail: "https://images.unsplash.com/photo-1551650975-87deedd944c3?w=800&q=80",
    previewImages: [],
    demoUrl: "https://demo.example.com",
    docsUrl: "https://docs.example.com",
    published: true,
    downloadCount: 234,
    fileUrl: "",
    fileName: "",
  },
  {
    title: "E-Commerce Template — React + Firebase",
    slug: "ecommerce-react-firebase",
    shortDescription: "Full-featured online store with cart, payments, and admin panel.",
    description: "A complete e-commerce solution built with React, Firebase, and Stripe. Includes product catalog, shopping cart, checkout flow, order management, customer dashboard, and a comprehensive admin panel for managing products, orders, and inventory.",
    price: 59,
    originalPrice: 99,
    category: "ecommerce",
    version: "1.5.2",
    techStack: ["React", "Firebase", "Stripe", "Tailwind CSS", "TypeScript"],
    features: [
      "Product catalog with search and filters",
      "Shopping cart with coupon codes",
      "Stripe payment integration",
      "Order tracking dashboard",
      "Admin product & inventory management",
      "Image upload to Firebase Storage",
      "Responsive mobile-first design",
    ],
    tags: ["react", "firebase", "ecommerce", "stripe", "typescript"],
    thumbnail: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80",
    previewImages: [],
    demoUrl: "https://demo.example.com",
    published: true,
    downloadCount: 187,
    fileUrl: "",
    fileName: "",
  },
  {
    title: "Admin Dashboard — React + Charts",
    slug: "admin-dashboard-react-charts",
    shortDescription: "Beautiful analytics dashboard with real-time charts and data tables.",
    description: "A highly customizable admin dashboard template built with React, Recharts, and Tailwind CSS. Features 20+ chart types, responsive data tables with sorting/filtering, user management, role-based access control, and a clean dark/light theme system.",
    price: 39,
    category: "admin-panels",
    version: "3.0.1",
    techStack: ["React", "Recharts", "Tailwind CSS", "TypeScript", "React Query"],
    features: [
      "20+ interactive chart components",
      "Sortable & filterable data tables",
      "Role-based access control",
      "Dark and light mode",
      "Fully responsive layout",
      "Export data to CSV/PDF",
      "Real-time data updates",
    ],
    tags: ["react", "dashboard", "charts", "admin", "analytics"],
    thumbnail: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80",
    previewImages: [],
    published: true,
    downloadCount: 412,
    fileUrl: "",
    fileName: "",
  },
  {
    title: "Mobile App Source — React Native Fitness",
    slug: "mobile-fitness-app-react-native",
    shortDescription: "Full fitness tracking app with workouts, nutrition, and progress charts.",
    description: "A complete React Native fitness app with workout tracking, nutrition logging, progress analytics, social features, and push notifications. Works on both iOS and Android. Includes a Node.js backend API and admin dashboard.",
    price: 99,
    originalPrice: 149,
    category: "mobile",
    version: "1.2.0",
    techStack: ["React Native", "Expo", "Node.js", "MongoDB", "TypeScript"],
    features: [
      "Workout plans and exercise library",
      "Nutrition and calorie tracking",
      "Progress charts and body measurements",
      "Social features and leaderboards",
      "Push notifications",
      "Offline support",
      "iOS and Android compatible",
    ],
    tags: ["react-native", "mobile", "fitness", "expo", "typescript"],
    thumbnail: "https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=800&q=80",
    previewImages: [],
    published: true,
    downloadCount: 98,
    fileUrl: "",
    fileName: "",
  },
  {
    title: "Landing Page Template — SaaS Marketing",
    slug: "landing-page-saas-marketing",
    shortDescription: "High-converting SaaS landing page with animations and pricing section.",
    description: "A professionally designed SaaS marketing landing page built with React and Framer Motion. Features hero section, feature highlights, pricing cards, testimonials, FAQ accordion, and newsletter signup. Optimized for conversion with A/B testing ready structure.",
    price: 29,
    category: "templates",
    version: "1.0.3",
    techStack: ["React", "Framer Motion", "Tailwind CSS", "TypeScript"],
    features: [
      "Animated hero with gradient background",
      "Feature grid with icon cards",
      "3-tier pricing table",
      "Customer testimonials carousel",
      "FAQ accordion",
      "Newsletter signup form",
      "Mobile responsive",
      "SEO optimized",
    ],
    tags: ["landing-page", "saas", "marketing", "react", "animations"],
    thumbnail: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80",
    previewImages: [],
    published: true,
    downloadCount: 521,
    fileUrl: "",
    fileName: "",
  },
  {
    title: "Full-Stack Blog Platform — Next.js + CMS",
    slug: "fullstack-blog-platform-nextjs",
    shortDescription: "SEO-optimized blog platform with markdown CMS, comments, and analytics.",
    description: "A complete blog platform built with Next.js 14 App Router, MDX for content, and a built-in CMS dashboard. Features SEO optimization, RSS feed, comment system, view analytics, tag/category system, and newsletter integration. Perfect for developers and content creators.",
    price: 49,
    category: "fullstack",
    version: "2.0.0",
    techStack: ["Next.js", "MDX", "TypeScript", "Tailwind CSS", "Vercel"],
    features: [
      "MDX-powered content with syntax highlighting",
      "Built-in CMS for content management",
      "SEO optimized with meta tags and sitemap",
      "Comment system with moderation",
      "View count analytics",
      "RSS feed generation",
      "Newsletter signup (ConvertKit)",
      "Tag and category system",
    ],
    tags: ["nextjs", "blog", "cms", "mdx", "typescript", "seo"],
    thumbnail: "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=800&q=80",
    previewImages: [],
    published: true,
    downloadCount: 163,
    fileUrl: "",
    fileName: "",
  },
];

export async function seedDemoProducts(): Promise<number> {
  let created = 0;
  for (const product of DEMO_PRODUCTS) {
    await createProduct(product as Parameters<typeof createProduct>[0]);
    created++;
  }
  return created;
}
