import { createProduct } from "./firestore";

const DEMO_PRODUCTS = [
  // ─── SaaS ───────────────────────────────────────────────────────────────────
  {
    title: "SaaS Starter Kit — Next.js + Stripe",
    slug: "saas-starter-nextjs-stripe",
    shortDescription: "Production-ready SaaS boilerplate with auth, billing, and admin dashboard.",
    description: "A complete SaaS starter kit built with Next.js 14, Tailwind CSS, Prisma ORM, and Stripe subscriptions. Includes multi-tenant auth, customer portal, webhook handling, team management, and a polished admin dashboard. Save 200+ hours of setup work.",
    price: 79,
    originalPrice: 129,
    category: "saas",
    version: "2.1.0",
    featured: true,
    techStack: ["Next.js", "TypeScript", "Tailwind CSS", "Prisma", "Stripe", "PostgreSQL"],
    features: [
      "Google & GitHub OAuth + Email Magic Link",
      "Stripe subscriptions with multiple pricing tiers",
      "Customer billing portal",
      "Admin dashboard with user management",
      "Team workspaces & invitations",
      "Email notifications (Resend)",
      "Dark/light mode",
      "Fully typed with TypeScript",
    ],
    tags: ["nextjs", "saas", "stripe", "typescript", "prisma"],
    thumbnail: "https://images.unsplash.com/photo-1551650975-87deedd944c3?w=800&q=80",
    previewImages: [],
    demoUrl: "https://demo.example.com",
    docsUrl: "https://docs.example.com",
    published: true,
    downloadCount: 234,
    fileUrl: "",
    fileName: "",
  },
  {
    title: "AI SaaS Boilerplate — GPT-4 + Subscription",
    slug: "ai-saas-boilerplate-gpt4",
    shortDescription: "Launch your AI-powered SaaS with OpenAI GPT-4, credits system, and Stripe.",
    description: "A fully-featured AI SaaS starter with OpenAI integration, credit-based usage billing, Stripe subscriptions, usage analytics, prompt management, and a clean user dashboard. Built with Next.js 14 App Router and Supabase.",
    price: 99,
    originalPrice: 159,
    category: "saas",
    version: "1.3.0",
    featured: true,
    techStack: ["Next.js", "OpenAI", "Supabase", "Stripe", "TypeScript", "Tailwind CSS"],
    features: [
      "OpenAI GPT-4 integration",
      "Credit-based usage system",
      "Stripe subscriptions + one-time payments",
      "Usage analytics dashboard",
      "Prompt templates management",
      "Rate limiting & throttling",
      "Supabase auth & database",
    ],
    tags: ["ai", "saas", "openai", "gpt4", "nextjs", "supabase"],
    thumbnail: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&q=80",
    previewImages: [],
    demoUrl: "https://demo.example.com",
    published: true,
    downloadCount: 318,
    fileUrl: "",
    fileName: "",
  },

  // ─── E-Commerce ────────────────────────────────────────────────────────────
  {
    title: "E-Commerce Template — React + Firebase",
    slug: "ecommerce-react-firebase",
    shortDescription: "Full-featured online store with cart, payments, and admin panel.",
    description: "A complete e-commerce solution built with React, Firebase, and Stripe. Includes product catalog, shopping cart, checkout flow, order management, customer dashboard, and a comprehensive admin panel for managing products, orders, and inventory.",
    price: 59,
    originalPrice: 99,
    category: "ecommerce",
    version: "1.5.2",
    techStack: ["React", "Firebase", "Stripe", "Tailwind CSS", "TypeScript"],
    features: [
      "Product catalog with search and filters",
      "Shopping cart with coupon codes",
      "Stripe payment integration",
      "Order tracking dashboard",
      "Admin product & inventory management",
      "Image upload to Firebase Storage",
      "Responsive mobile-first design",
    ],
    tags: ["react", "firebase", "ecommerce", "stripe", "typescript"],
    thumbnail: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80",
    previewImages: [],
    demoUrl: "https://demo.example.com",
    published: true,
    downloadCount: 187,
    fileUrl: "",
    fileName: "",
  },
  {
    title: "Multi-Vendor Marketplace — Laravel + Vue",
    slug: "multi-vendor-marketplace-laravel",
    shortDescription: "Scalable multi-vendor marketplace with seller dashboard and commission system.",
    description: "A full multi-vendor marketplace built with Laravel 11 and Vue 3. Features vendor onboarding, product listing approval, commission management, payout system, reviews, and a powerful admin panel. Ready for production deployment.",
    price: 89,
    originalPrice: 149,
    category: "ecommerce",
    version: "2.0.0",
    techStack: ["Laravel", "Vue 3", "MySQL", "Stripe", "Redis", "Tailwind CSS"],
    features: [
      "Multi-vendor onboarding system",
      "Commission & payout management",
      "Product listing approval workflow",
      "Buyer & seller chat",
      "Reviews and ratings",
      "Admin control panel",
      "Real-time notifications",
    ],
    tags: ["laravel", "vue", "marketplace", "multi-vendor", "php"],
    thumbnail: "https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=800&q=80",
    previewImages: [],
    published: true,
    downloadCount: 142,
    fileUrl: "",
    fileName: "",
  },

  // ─── Admin Panels ──────────────────────────────────────────────────────────
  {
    title: "Admin Dashboard — React + Charts",
    slug: "admin-dashboard-react-charts",
    shortDescription: "Beautiful analytics dashboard with real-time charts and data tables.",
    description: "A highly customizable admin dashboard template built with React, Recharts, and Tailwind CSS. Features 20+ chart types, responsive data tables with sorting/filtering, user management, role-based access control, and a clean dark/light theme system.",
    price: 39,
    category: "admin-panels",
    version: "3.0.1",
    featured: true,
    techStack: ["React", "Recharts", "Tailwind CSS", "TypeScript", "React Query"],
    features: [
      "20+ interactive chart components",
      "Sortable & filterable data tables",
      "Role-based access control",
      "Dark and light mode",
      "Fully responsive layout",
      "Export data to CSV/PDF",
      "Real-time data updates",
    ],
    tags: ["react", "dashboard", "charts", "admin", "analytics"],
    thumbnail: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80",
    previewImages: [],
    published: true,
    downloadCount: 412,
    fileUrl: "",
    fileName: "",
  },

  // ─── Mobile ────────────────────────────────────────────────────────────────
  {
    title: "Mobile App Source — React Native Fitness",
    slug: "mobile-fitness-app-react-native",
    shortDescription: "Full fitness tracking app with workouts, nutrition, and progress charts.",
    description: "A complete React Native fitness app with workout tracking, nutrition logging, progress analytics, social features, and push notifications. Works on both iOS and Android. Includes a Node.js backend API and admin dashboard.",
    price: 99,
    originalPrice: 149,
    category: "mobile",
    version: "1.2.0",
    techStack: ["React Native", "Expo", "Node.js", "MongoDB", "TypeScript"],
    features: [
      "Workout plans and exercise library",
      "Nutrition and calorie tracking",
      "Progress charts and body measurements",
      "Social features and leaderboards",
      "Push notifications",
      "Offline support",
      "iOS and Android compatible",
    ],
    tags: ["react-native", "mobile", "fitness", "expo", "typescript"],
    thumbnail: "https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=800&q=80",
    previewImages: [],
    published: true,
    downloadCount: 98,
    fileUrl: "",
    fileName: "",
  },
  {
    title: "Food Delivery App — Flutter + Firebase",
    slug: "food-delivery-flutter-firebase",
    shortDescription: "Full-featured food delivery app with real-time order tracking and driver app.",
    description: "A complete food delivery ecosystem built with Flutter. Includes customer app, restaurant dashboard, driver app, and admin panel. Features real-time GPS tracking, push notifications, Stripe payments, and restaurant menu management.",
    price: 129,
    originalPrice: 199,
    category: "mobile",
    version: "1.0.0",
    techStack: ["Flutter", "Dart", "Firebase", "Google Maps", "Stripe"],
    features: [
      "Customer, driver & restaurant apps",
      "Real-time GPS order tracking",
      "In-app chat support",
      "Stripe payment integration",
      "Push notifications",
      "Restaurant menu management",
      "Admin analytics dashboard",
    ],
    tags: ["flutter", "dart", "firebase", "food-delivery", "mobile"],
    thumbnail: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800&q=80",
    previewImages: [],
    published: true,
    downloadCount: 76,
    fileUrl: "",
    fileName: "",
  },

  // ─── Templates ─────────────────────────────────────────────────────────────
  {
    title: "Landing Page Template — SaaS Marketing",
    slug: "landing-page-saas-marketing",
    shortDescription: "High-converting SaaS landing page with animations and pricing section.",
    description: "A professionally designed SaaS marketing landing page built with React and Framer Motion. Features hero section, feature highlights, pricing cards, testimonials, FAQ accordion, and newsletter signup. Optimized for conversion with A/B testing ready structure.",
    price: 29,
    category: "templates",
    version: "1.0.3",
    techStack: ["React", "Framer Motion", "Tailwind CSS", "TypeScript"],
    features: [
      "Animated hero with gradient background",
      "Feature grid with icon cards",
      "3-tier pricing table",
      "Customer testimonials carousel",
      "FAQ accordion",
      "Newsletter signup form",
      "Mobile responsive",
      "SEO optimized",
    ],
    tags: ["landing-page", "saas", "marketing", "react", "animations"],
    thumbnail: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80",
    previewImages: [],
    published: true,
    downloadCount: 521,
    fileUrl: "",
    fileName: "",
  },
  {
    title: "Portfolio Template — Developer & Designer",
    slug: "portfolio-template-developer",
    shortDescription: "Stunning personal portfolio with project showcase and contact form.",
    description: "A beautifully crafted portfolio template for developers and designers. Built with Next.js and Framer Motion. Features animated project cards, skills section, timeline, blog integration, dark mode, and a contact form with email support.",
    price: 19,
    originalPrice: 39,
    category: "templates",
    version: "1.1.0",
    techStack: ["Next.js", "Framer Motion", "Tailwind CSS", "MDX"],
    features: [
      "Animated project showcase cards",
      "Skills & experience timeline",
      "Integrated blog with MDX",
      "Dark / light mode",
      "Contact form with email",
      "SEO optimized",
      "Mobile responsive",
    ],
    tags: ["portfolio", "developer", "designer", "nextjs", "animations"],
    thumbnail: "https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800&q=80",
    previewImages: [],
    published: true,
    downloadCount: 387,
    fileUrl: "",
    fileName: "",
  },

  // ─── Full-Stack ────────────────────────────────────────────────────────────
  {
    title: "Full-Stack Blog Platform — Next.js + CMS",
    slug: "fullstack-blog-platform-nextjs",
    shortDescription: "SEO-optimized blog platform with markdown CMS, comments, and analytics.",
    description: "A complete blog platform built with Next.js 14 App Router, MDX for content, and a built-in CMS dashboard. Features SEO optimization, RSS feed, comment system, view analytics, tag/category system, and newsletter integration.",
    price: 49,
    category: "fullstack",
    version: "2.0.0",
    techStack: ["Next.js", "MDX", "TypeScript", "Tailwind CSS", "Vercel"],
    features: [
      "MDX-powered content with syntax highlighting",
      "Built-in CMS for content management",
      "SEO optimized with meta tags and sitemap",
      "Comment system with moderation",
      "View count analytics",
      "RSS feed generation",
      "Newsletter signup",
      "Tag and category system",
    ],
    tags: ["nextjs", "blog", "cms", "mdx", "typescript", "seo"],
    thumbnail: "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=800&q=80",
    previewImages: [],
    published: true,
    downloadCount: 163,
    fileUrl: "",
    fileName: "",
  },
  {
    title: "Real Estate Platform — Django + React",
    slug: "real-estate-platform-django-react",
    shortDescription: "Property listing platform with map search, agent dashboard, and mortgage calc.",
    description: "A complete real estate listing platform built with Django REST Framework and React. Features property listings with Google Maps integration, advanced search filters, agent profiles, mortgage calculator, property inquiry system, and a full admin panel.",
    price: 119,
    originalPrice: 179,
    category: "fullstack",
    version: "1.4.0",
    techStack: ["Django", "React", "PostgreSQL", "Google Maps", "Celery", "Redis"],
    features: [
      "Property listings with photo galleries",
      "Google Maps property search",
      "Advanced search filters",
      "Agent profile pages",
      "Mortgage calculator",
      "Property inquiry & lead system",
      "Admin panel with analytics",
    ],
    tags: ["django", "react", "real-estate", "maps", "python"],
    thumbnail: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&q=80",
    previewImages: [],
    published: true,
    downloadCount: 89,
    fileUrl: "",
    fileName: "",
  },

  // ─── WordPress Templates ───────────────────────────────────────────────────
  {
    title: "WP Mega Menu Plugin — Drag & Drop Builder",
    slug: "wp-mega-menu-plugin",
    shortDescription: "Powerful WordPress mega menu plugin with visual drag-and-drop builder.",
    description: "A professional WordPress mega menu plugin with a visual drag-and-drop builder. Create stunning multi-column menus with icons, images, widgets, and custom HTML. Supports all themes, mobile responsive, and includes 20+ pre-built menu templates.",
    price: 29,
    originalPrice: 49,
    category: "wordpress",
    version: "3.2.1",
    featured: true,
    techStack: ["PHP", "WordPress", "JavaScript", "CSS3", "jQuery"],
    features: [
      "Drag-and-drop visual menu builder",
      "Multi-column mega menu layouts",
      "Icon and image support in menus",
      "Widget areas in menu items",
      "20+ pre-built menu templates",
      "Mobile responsive menus",
      "Works with any WordPress theme",
      "WooCommerce category menus",
    ],
    tags: ["wordpress", "plugin", "menu", "navigation", "php"],
    thumbnail: "https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?w=800&q=80",
    previewImages: [],
    demoUrl: "https://demo.example.com",
    published: true,
    downloadCount: 294,
    fileUrl: "",
    fileName: "",
  },
  {
    title: "WP Booking & Appointment Plugin",
    slug: "wp-booking-appointment-plugin",
    shortDescription: "Full-featured WordPress booking plugin with calendar, payments, and notifications.",
    description: "A complete booking and appointment management plugin for WordPress. Perfect for salons, clinics, consultants, and service businesses. Includes online booking calendar, PayPal/Stripe payments, email/SMS notifications, staff management, and a customer dashboard.",
    price: 49,
    originalPrice: 79,
    category: "wordpress",
    version: "2.5.0",
    techStack: ["PHP", "WordPress", "MySQL", "Stripe", "Twilio", "JavaScript"],
    features: [
      "Interactive booking calendar",
      "Multiple service & staff management",
      "Stripe & PayPal payments",
      "Email & SMS reminders",
      "Customer booking dashboard",
      "Recurring appointments",
      "Google Calendar sync",
      "WooCommerce compatible",
    ],
    tags: ["wordpress", "plugin", "booking", "appointment", "php", "stripe"],
    thumbnail: "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=800&q=80",
    previewImages: [],
    demoUrl: "https://demo.example.com",
    published: true,
    downloadCount: 178,
    fileUrl: "",
    fileName: "",
  },
  {
    title: "WP Advanced Forms Builder — Drag & Drop",
    slug: "wp-advanced-forms-builder",
    shortDescription: "Create unlimited forms with conditional logic, file uploads, and multi-step flows.",
    description: "A powerful WordPress form builder plugin with a visual drag-and-drop interface. Build contact forms, surveys, order forms, and multi-step wizards. Includes conditional logic, file uploads, email notifications, spam protection, and 20+ field types.",
    price: 35,
    category: "wordpress",
    version: "4.1.0",
    techStack: ["PHP", "WordPress", "jQuery", "AJAX", "MySQL"],
    features: [
      "Drag-and-drop form builder",
      "20+ field types",
      "Conditional logic & branching",
      "Multi-step form wizard",
      "File & image uploads",
      "Email notifications",
      "Spam protection (reCAPTCHA)",
      "CSV export of submissions",
    ],
    tags: ["wordpress", "plugin", "forms", "drag-drop", "php"],
    thumbnail: "https://images.unsplash.com/photo-1434626881859-194d67b2b86f?w=800&q=80",
    previewImages: [],
    published: true,
    downloadCount: 321,
    fileUrl: "",
    fileName: "",
  },

  // ─── Blogger Templates ─────────────────────────────────────────────────────
  {
    title: "TechMag — Technology Blogger Template",
    slug: "techmag-blogger-template",
    shortDescription: "Premium tech magazine Blogger template with fast loading and AdSense ready.",
    description: "A professional technology magazine Blogger template with a modern grid layout, dark/light mode, featured post slider, related posts, author box, and social sharing. Fully optimized for Google AdSense, Core Web Vitals, and SEO. Mobile responsive and 100% Blogger compatible.",
    price: 19,
    originalPrice: 35,
    category: "blogger",
    version: "2.0.0",
    featured: true,
    techStack: ["Blogger XML", "CSS3", "JavaScript", "HTML5"],
    features: [
      "Magazine-style grid layout",
      "Dark / light mode toggle",
      "Featured post slider",
      "Related posts section",
      "Author bio box",
      "Social sharing buttons",
      "AdSense ad placements",
      "SEO & Core Web Vitals optimized",
    ],
    tags: ["blogger", "template", "magazine", "tech", "adsense", "seo"],
    thumbnail: "https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=800&q=80",
    previewImages: [],
    demoUrl: "https://demo.example.com",
    published: true,
    downloadCount: 443,
    fileUrl: "",
    fileName: "",
  },
  {
    title: "MiniBlog — Clean Minimal Blogger Template",
    slug: "miniblog-minimal-blogger",
    shortDescription: "Ultra-clean minimal Blogger template focused on readability and fast performance.",
    description: "A beautifully minimal Blogger template designed for writers and content creators. Features a distraction-free reading experience, beautiful typography, smooth animations, newsletter widget, category navigation, and perfect Core Web Vitals scores.",
    price: 15,
    category: "blogger",
    version: "1.2.0",
    techStack: ["Blogger XML", "CSS3", "JavaScript", "HTML5"],
    features: [
      "Minimal distraction-free layout",
      "Beautiful typography system",
      "Newsletter subscription widget",
      "Category & label navigation",
      "Table of contents",
      "Smooth scroll animations",
      "Lightning-fast performance",
      "Mobile first responsive",
    ],
    tags: ["blogger", "template", "minimal", "writing", "clean"],
    thumbnail: "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&q=80",
    previewImages: [],
    published: true,
    downloadCount: 276,
    fileUrl: "",
    fileName: "",
  },
  {
    title: "ShopBlog — Blogger eCommerce Template",
    slug: "shopblog-blogger-ecommerce",
    shortDescription: "Blogger template with built-in product showcase and WhatsApp order buttons.",
    description: "A unique Blogger template that combines blogging with e-commerce features. Includes a product grid, individual product pages, WhatsApp order button, price display, image gallery, and a deal countdown timer. Perfect for small businesses using Blogger.",
    price: 25,
    originalPrice: 40,
    category: "blogger",
    version: "1.5.0",
    techStack: ["Blogger XML", "CSS3", "JavaScript", "HTML5"],
    features: [
      "Product grid and listing pages",
      "WhatsApp order button",
      "Price & discount display",
      "Image gallery lightbox",
      "Countdown deal timer",
      "Category filter system",
      "Contact form widget",
      "AdSense ready",
    ],
    tags: ["blogger", "template", "ecommerce", "shop", "whatsapp"],
    thumbnail: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&q=80",
    previewImages: [],
    published: true,
    downloadCount: 198,
    fileUrl: "",
    fileName: "",
  },

  // ─── Shopify Templates ─────────────────────────────────────────────────────
  {
    title: "LuxStore — Premium Shopify Theme",
    slug: "luxstore-shopify-theme",
    shortDescription: "High-converting luxury Shopify theme with mega menu and product quick view.",
    description: "A premium Shopify 2.0 theme designed for luxury and fashion brands. Features a mega menu, product quick view, lookbook sections, size guide modal, upsell recommendations, wishlist, and advanced filtering. Optimized for mobile conversion and page speed.",
    price: 69,
    originalPrice: 119,
    category: "shopify",
    version: "3.1.0",
    featured: true,
    techStack: ["Shopify Liquid", "JavaScript", "CSS3", "Shopify 2.0"],
    features: [
      "Mega menu with image support",
      "Product quick view modal",
      "Lookbook & lifestyle sections",
      "Size guide popup",
      "Product upsell & cross-sell",
      "Wishlist functionality",
      "Advanced product filtering",
      "Fast mobile performance",
    ],
    tags: ["shopify", "theme", "luxury", "fashion", "ecommerce", "liquid"],
    thumbnail: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&q=80",
    previewImages: [],
    demoUrl: "https://demo.example.com",
    published: true,
    downloadCount: 231,
    fileUrl: "",
    fileName: "",
  },
  {
    title: "GreenLife — Eco & Organic Shopify Theme",
    slug: "greenlife-eco-shopify-theme",
    shortDescription: "Beautiful organic and eco-friendly Shopify theme with subscription support.",
    description: "A clean and earthy Shopify 2.0 theme built for organic, eco-friendly, and wellness brands. Features subscription product support, ingredient highlight sections, sustainability badges, video backgrounds, newsletter popup, and age-gate. Perfect for food, beauty, and health brands.",
    price: 55,
    category: "shopify",
    version: "2.0.0",
    techStack: ["Shopify Liquid", "JavaScript", "CSS3", "Shopify 2.0"],
    features: [
      "Subscription product support",
      "Ingredient highlight sections",
      "Eco/sustainability badges",
      "Video background hero",
      "Newsletter popup",
      "Product ingredient list",
      "Age verification gate",
      "Green-themed design system",
    ],
    tags: ["shopify", "theme", "organic", "eco", "wellness", "subscription"],
    thumbnail: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&q=80",
    previewImages: [],
    published: true,
    downloadCount: 167,
    fileUrl: "",
    fileName: "",
  },
  {
    title: "TechGear — Electronics Shopify Theme",
    slug: "techgear-electronics-shopify",
    shortDescription: "Feature-rich Shopify theme for electronics stores with spec tables and comparison.",
    description: "A powerful Shopify 2.0 theme built for electronics and gadget stores. Includes product specification tables, product comparison, 360° product view, video integration, bundle builder, flash sale countdown, and advanced variant display for products with many options.",
    price: 75,
    originalPrice: 120,
    category: "shopify",
    version: "1.8.0",
    techStack: ["Shopify Liquid", "JavaScript", "CSS3", "Shopify 2.0"],
    features: [
      "Product specification tables",
      "Product comparison feature",
      "360° product image viewer",
      "Video product demos",
      "Bundle product builder",
      "Flash sale countdown timer",
      "Advanced variant swatches",
      "Stock urgency indicators",
    ],
    tags: ["shopify", "theme", "electronics", "tech", "gadgets", "comparison"],
    thumbnail: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80",
    previewImages: [],
    published: true,
    downloadCount: 203,
    fileUrl: "",
    fileName: "",
  },

  // ─── Browser Extensions ────────────────────────────────────────────────────
  {
    title: "Chrome Productivity Extension — Tab Manager",
    slug: "chrome-tab-manager-extension",
    shortDescription: "Beautiful Chrome extension source code for managing tabs, sessions, and bookmarks.",
    description: "A complete Chrome extension source code for tab management and productivity. Features tab grouping, session saving/restoring, quick bookmark access, distraction blocking, focus timer, and a clean popup UI. Built with Manifest V3 and React. Great starting point for your own extension.",
    price: 35,
    originalPrice: 55,
    category: "extensions",
    version: "1.0.0",
    featured: true,
    techStack: ["JavaScript", "React", "Chrome Extension MV3", "Tailwind CSS", "Vite"],
    features: [
      "Tab grouping by domain or custom",
      "Session save and restore",
      "Quick bookmark search",
      "Distraction blocking list",
      "Focus / Pomodoro timer",
      "Keyboard shortcuts",
      "Sync across devices",
      "Manifest V3 compatible",
    ],
    tags: ["chrome", "extension", "productivity", "tabs", "javascript", "react"],
    thumbnail: "https://images.unsplash.com/photo-1555066931-4365d14431b4?w=800&q=80",
    previewImages: [],
    published: true,
    downloadCount: 156,
    fileUrl: "",
    fileName: "",
  },
  {
    title: "Price Tracker Extension — Amazon & eBay",
    slug: "price-tracker-browser-extension",
    shortDescription: "Browser extension that tracks price history and sends drop alerts for any product.",
    description: "A cross-browser extension (Chrome + Firefox) that tracks product prices on Amazon, eBay, and other e-commerce sites. Features price history charts, customizable drop alerts via email/browser notification, wishlist tracking, and a comparison view. Includes a Node.js backend for price crawling.",
    price: 59,
    category: "extensions",
    version: "2.1.0",
    techStack: ["JavaScript", "Vue 3", "Chrome & Firefox Extension", "Node.js", "MongoDB"],
    features: [
      "Price history chart overlay",
      "Customizable price drop alerts",
      "Email & push notifications",
      "Amazon & eBay support",
      "Wishlist price tracking",
      "Price comparison across sites",
      "Node.js price crawling backend",
      "Chrome & Firefox compatible",
    ],
    tags: ["extension", "price-tracker", "amazon", "ebay", "javascript", "vue"],
    thumbnail: "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800&q=80",
    previewImages: [],
    published: true,
    downloadCount: 112,
    fileUrl: "",
    fileName: "",
  },
  {
    title: "AI Writing Assistant Extension — GPT-4",
    slug: "ai-writing-assistant-extension",
    shortDescription: "Browser extension with GPT-4 writing assistant, text improver, and email composer.",
    description: "A powerful browser extension that adds AI writing capabilities to any text field on any website. Features tone adjustment, grammar fixing, email composition, summarization, translation, and custom prompt templates. Works with Gmail, LinkedIn, Twitter, and any website.",
    price: 45,
    originalPrice: 75,
    category: "extensions",
    version: "1.5.0",
    techStack: ["JavaScript", "React", "OpenAI API", "Chrome Extension MV3", "Tailwind CSS"],
    features: [
      "One-click text improvement",
      "Tone adjustment (formal, casual, etc.)",
      "Grammar & spelling correction",
      "Email composition assistant",
      "Text summarization",
      "Multi-language translation",
      "Custom prompt templates",
      "Works on any website",
    ],
    tags: ["extension", "ai", "writing", "gpt4", "openai", "productivity"],
    thumbnail: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&q=80",
    previewImages: [],
    published: true,
    downloadCount: 289,
    fileUrl: "",
    fileName: "",
  },
];

export async function seedDemoProducts(): Promise<number> {
  let created = 0;
  for (const product of DEMO_PRODUCTS) {
    try {
      await createProduct(product as Parameters<typeof createProduct>[0]);
      created++;
    } catch {
      // skip duplicates silently
    }
  }
  return created;
}
